name: "freshfromfarm CICD deploy"

on:
  push:
    branches: ["master"]

env:
  REACT_APP_BACKEND: ${{ secrets.REACT_APP_BACKEND }}
  RAZORPAY_KEY_ID: ${{ secrets.RAZORPAY_KEY_ID }}
  RAZORPAY_KEY_SECRET: ${{ secrets.RAZORPAY_KEY_SECRET }}
  DATABASE: ${{ secrets.DATABASE }}
  SECRET: ${{ secrets.SECRET }}
  AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
  AWS_BUCKET_REGION: ${{ secrets.AWS_BUCKET_REGION }}
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
  TEST_TOKEN: "This will work or not"

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Creting env file on client
        run: |
          cd client
          sudo touch .env
          sudo echo REACT_APP_BACKEND= ${{ secrets.REACT_APP_BACKEND }} >> .env
          sudo echo RAZORPAY_KEY_ID= ${{ secrets.RAZORPAY_KEY_ID }} >> .env
          sudo echo RAZORPAY_KEY_SECRET= ${{ secrets.RAZORPAY_KEY_SECRET }} >> .env
          npm i
          npm run build
          sudo mv build ../server/static
          cd ../server
          sudo touch .env
          sudo echo DATABASE= ${{ secrets.DATABASE }} >> .env
          echo SECRET= ${{ secrets.SECRET }} >> .env
          echo RAZORPAY_KEY_ID= ${{ secrets.RAZORPAY_KEY_ID }} >> .env
          echo RAZORPAY_KEY_SECRET= ${{ secrets.RAZORPAY_KEY_SECRET }} >> .env
          echo AWS_BUCKET_NAME= ${{ secrets.AWS_BUCKET_NAME }} >> .env
          echo AWS_BUCKET_REGION= ${{ secrets.AWS_BUCKET_REGION }} >> .env
          echo AWS_ACCESS_KEY= ${{ secrets.AWS_ACCESS_KEY }} >> .env
          sudo echo AWS_SECRET_KEY= ${{ secrets.AWS_SECRET_KEY }} >> .env
          npm i
          pm2 stop 0
          pm2 start 0
          pm2 save
          sudo service nginx restart
      - name: Setup finish
        run: echo "Deployment completed"
